/**
 * Single catalog for grid + sphere. Production URLs only — no local ports.
 */
export const APPS = [
  {
    id: "govdash-app",
    name: "GovDash",
    href: "https://govdash.markmaga.com",
    img: "images/ss-govdash.webp?v=3",
    imgW: 900,
    imgH: 1838,
    hint: "Citizen map of the U.S. federal government · Icicle Tree Circles Sankey",
  },
  {
    id: "supermars-app",
    name: "SuperMars",
    href: "https://supermars.markmaga.com",
    img: "images/ss-supermars.webp",
    imgW: 900,
    imgH: 1863,
    hint: "Hi-res 3D Mars · live phase for your place · rise high set",
  },
  {
    id: "spacexplor-app",
    name: "SpaceXplore",
    href: "https://spacexplore.markmaga.com",
    img: "images/ss-spacexplore.webp",
    imgW: 900,
    imgH: 1854,
    hint: "Next flight · ops & specs for all programs · sites map",
  },
  {
    id: "supermoon-app",
    name: "SuperMoon",
    href: "https://supermoon.markmaga.com",
    img: "images/ss-supermoon.webp",
    imgW: 900,
    imgH: 1862,
    hint: "Hi-res 3D Moon · live phase for your place · rise high set · tides",
  },
  {
    id: "solardashboard-app",
    name: "Solar Dashboard",
    href: "https://solardashboard.markmaga.com",
    img: "images/ss-solardashboard.webp",
    imgW: 900,
    imgH: 1847,
    hint: "UV · irradiance · air · pollen · sky path · skin type burn time",
  },
  {
    id: "lightslice-app",
    name: "LightSlice",
    href: "https://lightslice.markmaga.com",
    img: "images/ss-lightslice.webp",
    imgW: 900,
    imgH: 1876,
    hint: "Live camera spectral band · Drag LO/HI · ROYGBIV",
  },
  {
    id: "hypermiler-app",
    name: "HyperMiler",
    href: "https://hypermiler.markmaga.com",
    img: "images/ss-hypermiler.webp",
    imgW: 900,
    imgH: 1860,
    hint: "Live accel, brake, corner, bump g · Smooth score · GPS speed",
  },
  {
    id: "audioslice-app",
    name: "AudioSlice",
    href: "https://audioslice.markmaga.com",
    img: "images/ss-audioslice.webp",
    imgW: 900,
    imgH: 1856,
    hint: "Live mic spectrogram · Move LO/HI · WIRED HEADPHONES",
    hintHtml:
      'Live mic spectrogram · Move LO/HI · <span class="hint-white">WIRED HEADPHONES</span>',
  },
  {
    id: "lifespan-app",
    name: "Lifespan",
    href: "https://lifespan.markmaga.com",
    img: "images/ss-lifespan.webp",
    imgW: 900,
    imgH: 1842,
    hint: "Slide age, height, weight, VO2 and habits · see BMI, remaining years",
  },
  {
    id: "elevation-app",
    name: "US Elevation Map",
    href: "https://elevation.markmaga.com",
    img: "images/ss-elevation.webp",
    imgW: 900,
    imgH: 1852,
    hint: "Tap the map for elevation · Tap save to add second point",
  },
  {
    id: "solar-system-app",
    name: "Solar System",
    href: "https://solarsystem.markmaga.com",
    img: "images/ss-solarsystem.webp?v=3",
    imgW: 900,
    imgH: 1853,
    hint: "3D Sun, planets, moons, and Pluto · slide time · tap a planet",
  },
  {
    id: "calamityville-app",
    name: "CalamityVille",
    href: "https://calamityville.markmaga.com",
    img: "images/ss-calamityville.webp",
    imgW: 900,
    imgH: 1864,
    hint: "Live disasters on a 3D Earth · quakes · storms · fires",
  },
  {
    id: "satellite-app",
    name: "Orbital View",
    href: "https://orbital.markmaga.com",
    img: "images/ss-orbitalview.webp",
    imgW: 900,
    imgH: 1851,
    hint: "3D Earth and live satellites · slide time · tap Constellations",
  },
  {
    id: "solar-light-app",
    name: "Solar Light",
    href: "https://solar.markmaga.com",
    img: "images/ss-solarlight.webp",
    imgW: 900,
    imgH: 1854,
    hint: "Slide time to see sunlight as % of solar noon",
  },
  {
    id: "suction-cup-app",
    name: "The Weight of Air and the Suction Cup",
    href: "https://air.markmaga.com",
    img: "images/ss-suctioncup.webp",
    imgW: 900,
    imgH: 1846,
    hint: "Live pressure at your location · slide cup and vacuum",
  },
  {
    id: "moon-phase-app",
    name: "Today's Moon",
    href: "https://themoon.markmaga.com",
    img: "images/ss-todaysmoon.webp",
    imgW: 900,
    imgH: 1836,
    hint: "Drag slider for phases · tap moon for red · pinch to zoom",
  },
  {
    id: "faucipies-app",
    name: "FauciPies",
    href: "https://faucipies.markmaga.com",
    img: "images/ss-faucipies.webp",
    imgW: 900,
    imgH: 1847,
    hint: "Pick a pie · wind up · let fly · cream splat reveals the story",
  },
  {
    id: "spacetime-app",
    name: "SpaceTime",
    href: "https://spacetime.markmaga.com",
    img: "images/ss-spacetime.webp",
    imgW: 900,
    imgH: 1856,
    hint: "PROTOTYPE · Record a 3D path in time · GPS + IMU",
    hintHot: "PROTOTYPE",
    hintHtml:
      '<span class="hint-red">PROTOTYPE</span> · Record a 3D path in time · GPS + IMU',
  },
];
