/**
 * Single catalog for grid + sphere. Production URLs only — no local ports.
 */
export const APPS = [
  {
    id: "globalflows-app",
    name: "GlobalFlows",
    href: "https://globalflows.markmaga.com",
    img: "images/ss-globalflows.webp?v=8",
    imgW: 1124,
    imgH: 2346,
    hint: "Live global money machine · liquidity · rates · growth · inflation · risk",
  },
  {
    id: "bubblincrude-app",
    name: "BubblinCrude",
    href: "https://bubblincrude.markmaga.com",
    img: "images/ss-bubblincrude.webp?v=8",
    imgW: 1124,
    imgH: 2345,
    hint: "Global crude streams · filter, assay, compare WTI, Merey-16, Boscan",
  },
  {
    id: "moleculefactory-app",
    name: "MoleculeFactory",
    href: "https://moleculefactory.markmaga.com",
    img: "images/ss-moleculefactory.webp?v=8",
    imgW: 1124,
    imgH: 2327,
    hint: "Build molecules in 3D · library stories · free-build from the table",
  },
  {
    id: "govdash-app",
    name: "GovDash",
    href: "https://govdash.markmaga.com",
    img: "images/ss-govdash.webp?v=8",
    imgW: 1124,
    imgH: 2296,
    hint: "Citizen map of the U.S. federal government · Icicle Tree Circles Sankey",
  },
  {
    id: "supermars-app",
    name: "SuperMars",
    href: "https://supermars.markmaga.com",
    img: "images/ss-supermars.webp?v=8",
    imgW: 1170,
    imgH: 2532,
    hint: "Hi-res 3D Mars · live phase for your place · rise high set",
  },
  {
    id: "spacexplor-app",
    name: "SpaceXplore",
    href: "https://spacexplore.markmaga.com",
    img: "images/ss-spacexplore.webp?v=8",
    imgW: 1124,
    imgH: 2316,
    hint: "Next flight · ops & specs for all programs · sites map",
  },
  {
    id: "satellite-app",
    name: "Orbital View",
    href: "https://orbital.markmaga.com",
    img: "images/ss-orbitalview.webp?v=8",
    imgW: 1124,
    imgH: 2315,
    hint: "3D Earth and live satellites · slide time · tap Constellations",
  },
  {
    id: "supermoon-app",
    name: "SuperMoon",
    href: "https://supermoon.markmaga.com",
    img: "images/ss-supermoon.webp?v=8",
    imgW: 1170,
    imgH: 2532,
    hint: "Hi-res 3D Moon · live phase for your place · rise high set · tides",
  },
  {
    id: "solardashboard-app",
    name: "Solar Dashboard",
    href: "https://solardashboard.markmaga.com",
    img: "images/ss-solardashboard.webp?v=8",
    imgW: 1124,
    imgH: 2307,
    hint: "UV · irradiance · air · pollen · sky path · skin type burn time",
  },
  {
    id: "lightslice-app",
    name: "LightSlice",
    href: "https://lightslice.markmaga.com",
    img: "images/ss-lightslice.webp?v=8",
    imgW: 1124,
    imgH: 2343,
    hint: "Live camera spectral band · Drag LO/HI · ROYGBIV",
  },
  {
    id: "hypermiler-app",
    name: "HyperMiler",
    href: "https://hypermiler.markmaga.com",
    img: "images/ss-hypermiler.webp?v=8",
    imgW: 1123,
    imgH: 2321,
    hint: "Live accel, brake, corner, bump g · Smooth score · GPS speed",
  },
  {
    id: "audioslice-app",
    name: "AudioSlice",
    href: "https://audioslice.markmaga.com",
    img: "images/ss-audioslice.webp?v=8",
    imgW: 1124,
    imgH: 2318,
    hint: "Live mic spectrogram · Move LO/HI · WIRED HEADPHONES",
    hintHtml:
      'Live mic spectrogram · Move LO/HI · <span class="hint-white">WIRED HEADPHONES</span>',
  },
  {
    id: "lifespan-app",
    name: "Lifespan",
    href: "https://lifespan.markmaga.com",
    img: "images/ss-lifespan.webp?v=8",
    imgW: 1124,
    imgH: 2301,
    hint: "Slide age, height, weight, VO2 and habits · see BMI, remaining years",
  },
  {
    id: "elevation-app",
    name: "US Elevation Map",
    href: "https://elevation.markmaga.com",
    img: "images/ss-elevation.webp?v=8",
    imgW: 1124,
    imgH: 2313,
    hint: "Tap the map for elevation · Tap save to add second point",
  },
  {
    id: "solar-system-app",
    name: "Solar System",
    href: "https://solarsystem.markmaga.com",
    img: "images/ss-solarsystem.webp?v=8",
    imgW: 1124,
    imgH: 2314,
    hint: "3D Sun, planets, moons, and Pluto · slide time · tap a planet",
  },
  {
    id: "calamityville-app",
    name: "CalamityVille",
    href: "https://calamityville.markmaga.com",
    img: "images/ss-calamityville.webp?v=8",
    imgW: 1124,
    imgH: 2328,
    hint: "Live disasters on a 3D Earth · quakes · storms · fires",
  },
  {
    id: "solar-light-app",
    name: "Solar Light",
    href: "https://solar.markmaga.com",
    img: "images/ss-solarlight.webp?v=8",
    imgW: 1124,
    imgH: 2316,
    hint: "Slide time to see sunlight as % of solar noon",
  },
  {
    id: "suction-cup-app",
    name: "The Weight of Air and the Suction Cup",
    href: "https://air.markmaga.com",
    img: "images/ss-suctioncup.webp?v=8",
    imgW: 1124,
    imgH: 2305,
    hint: "Live pressure at your location · slide cup and vacuum",
  },
  {
    id: "moon-phase-app",
    name: "Today's Moon",
    href: "https://themoon.markmaga.com",
    img: "images/ss-todaysmoon.webp?v=8",
    imgW: 1124,
    imgH: 2293,
    hint: "Drag slider for phases · tap moon for red · pinch to zoom",
  },
  {
    id: "faucipies-app",
    name: "FauciPies",
    href: "https://faucipies.markmaga.com",
    img: "images/ss-faucipies.webp?v=8",
    imgW: 1124,
    imgH: 2307,
    hint: "Pick a pie · wind up · let fly · cream splat reveals the story",
  },
  {
    id: "spacetime-app",
    name: "SpaceTime",
    href: "https://spacetime.markmaga.com",
    img: "images/ss-spacetime.webp?v=8",
    imgW: 1124,
    imgH: 2318,
    hint: "PROTOTYPE · Record a 3D path in time · GPS + IMU",
    hintHot: "PROTOTYPE",
    hintHtml:
      '<span class="hint-red">PROTOTYPE</span> · Record a 3D path in time · GPS + IMU',
  },
];
